[package]
name = "finite_difference_thermal_model"
version = "0.1.0"
authors = ["German Molina <germolinal@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
calendar = { path = "../../calendar" }
communication_traits = { path="../../communication_traits" }
geometry3d = {path = "../../geometry3d"}
building_model = {path = "../../building_model"}
matrix = {path = "../../matrix"}
convection = {path = "../convection"}
gas_properties = {path = "../gas_properties"}
weather = {path = "../../weather"}

[dev-dependencies]
schedule = { path = "../../schedule" }
weather = { path = "../../weather" }
calendar = { path = "../../calendar" }