[package]
name = "finite_difference_thermal_model"
version = "0.1.0"
authors = ["German Molina <germolinal@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
calendar = { path = "../../calendar" }
weather = {path = "../../weather"}
building_model = {path = "../../building_model"}
simulation_state = { path = "../../simulation_state" }
communication_protocols = { path = "../../communication_protocols" }
geometry3d = {path = "../../geometry3d"}
matrix = {path = "../../matrix"}
convection = {path = "../convection"}
gas_properties = {path = "../gas_properties"}

[dev-dependencies]
schedule = { path = "../../schedule" }
weather = { path = "../../weather" }
calendar = { path = "../../calendar" }
simple_test_buildings = {path="../../simple_test_buildings"}

# Check https://stackoverflow.com/questions/53127722/how-can-i-activate-features-in-all-my-crates

[package.metadata.docs.rs]
rustdoc-args = [
    "--html-in-header",
    "./katex.html",
]