on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

name: Build

jobs:
  build_and_test:
    name: Build project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: build
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: features --features float

          
