name: Tests

on:
  push:
    branches: [ dev, main ]
  pull_request:
    branches: [ dev, main ]

env:
  CARGO_TERM_COLOR: always

jobs:  
  test_default:
    runs-on: ubuntu-latest     
    steps:
    - uses: actions/checkout@v3 
    - name: Run tests
      run: cargo test --verbose
  test_parallel:
    runs-on: ubuntu-latest     
    steps:
    - uses: actions/checkout@v3 
    - name: Run tests
      run: cargo test --verbose --features parallel
  # test_float:
  #   runs-on: ubuntu-latest     
  #   steps:
  #   - uses: actions/checkout@v3 
  #   - name: Run tests
  #     run: cargo test --features float --verbose     
  