name: TestAndDeployDoc

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
    - name: report
      run: |        
        ls
  setup:
    runs-on: ubuntu-latest
    steps:
    - name: setup
      run: |
        rustup component add llvm-tools-preview
        rustup default nightly
        cargo install grcov
        export RUSTFLAGS="-Zinstrument-coverage"
        export LLVM_PROFILE_FILE="thermal-%p-%m.profraw"        
  build:
    runs-on: ubuntu-latest
    needs: setup
    steps:
    - name: Build
      run: cargo build --verbose
  build_float:
    needs: setup
    runs-on: ubuntu-latest
    steps:
    - name: Build Float
      run: cargo build --verbose --features float --features simple_test_models/float
  test:
    runs-on: ubuntu-latest 
    needs: build
    steps:
    - name: Run tests
      run: cargo test --verbose 
  # test_float:
  #   runs-on: ubuntu-latest
  #   needs: build_float
  #   steps:     
  #   - name: Run tests Float
  #     run: cargo test --verbose  --features float --features simple_test_models/float
  docs:    
    runs-on: ubuntu-latest
    steps:
    - name: Build doc
      run: RUSTDOCFLAGS="--html-in-header katex.html" cargo doc --document-private-items --no-deps
    - name: Set Index
      run: echo '<meta http-equiv=refresh content=0;url=thermal/index.html>' > target/doc/index.html
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@4.1.5
      with:
        branch: gh-pages # The branch the action should deploy to.
        folder: target/doc/ # The folder the action should deploy.
  coverage: 
    runs-on: ubuntu-latest
    needs: [build, test]
    steps: 
    - name: get coverage
      run: grcov . -s . --binary-path ./target/debug/ -t html --branch --ignore-not-existing -o ./coverage/
